@baseURL = http://localhost:3030

@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzkxNGVmYWVlYzEyMjdhZmM4ZDciLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NDQ2MjA5MCwiZXhwIjoxNjgwMDE0MDkwfQ.-VlBsvmRLEPkh02LERdCoTkZPuqzybfW2ILk_DJSJXg

###

// Get all bookings
GET {{baseURL}}/bookings
Authorization: Bearer {{bearer}}

###

// Create booking 
POST {{baseURL}}/bookings
Authorization: Bearer {{bearer}}
Content-Type: application/json

{
    "address": "Toivo street",
    "startdate": "2022-10-26",
    "enddate": "2022-10-30"
}

###

// Modify booking
PATCH  {{baseURL}}/bookings/633191d8abd631659501ecca
Authorization: Bearer {{bearer}}
Content-Type: application/json

{
    "enddate": "27-12-2022"
}

###

// Delete booking
DELETE {{baseURL}}/bookings/633436b0867c39b442477df0
Authorization: Bearer {{bearer}}