@baseURL = http://localhost:3030

@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzkxNGVmYWVlYzEyMjdhZmM4ZDciLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NDM2NDI0NiwiZXhwIjoxNjc5OTE2MjQ2fQ.wu7qhypMQwF4dWdu3SJeLywk8JjejNWWKPwkd1SlDWM

###

// Get all bookings
GET {{baseURL}}/bookings
Authorization: Bearer {{bearer}}

###

// Create booking 
POST {{baseURL}}/bookings
Authorization: Bearer {{bearer}}
Content-Type: application/json

{
    "address": "Cabin street 22",
    "startdate": "2022-10-20",
    "enddate": "2022-10-25"
}

###

// Modify booking
PATCH  {{baseURL}}/bookings/633191d8abd631659501ecca
Authorization: Bearer {{bearer}}
Content-Type: application/json

{
    "enddate": "27-12-2022"
}

###

// Delete booking
DELETE {{baseURL}}/bookings/633436b0867c39b442477df0
Authorization: Bearer {{bearer}}