@baseURL = http://localhost:3030
@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzg1OGVmYWVlYzEyMjdhZmM4ZDIiLCJlbWFpbCI6ImphbmUuZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NDUzNzkyNiwiZXhwIjoxNjgwMDg5OTI2fQ.vXMbkl0Uj0P-wI0vCaddguhqukwTjPNiJGb6EVs5_Zw

###

// Get all cabins
GET {{baseURL}}/cabins
Authorization: Bearer {{bearer}}

###

// Create new cabin
POST {{baseURL}}/cabins
Content-Type: application/json
Authorization: Bearer {{bearer}}

{
    "address": "Rasmus' cabin",
    "size": 28,
    "sauna": false,
    "beach": false,
    "rent": 25
}

###

// Patch/modify cabin data
PATCH {{baseURL}}/cabins/63342c4633edd0eaf467fd4b
Content-Type: application/json
Authorization: Bearer {{bearer}}

{
    "address": "Cabin street"
}

###

// Delete cabin
DELETE {{baseURL}}/cabins/6334055a161a5d84aa2d2fae
Authorization: Bearer {{bearer}}
