@baseURL = http://localhost:3030
@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzkxNGVmYWVlYzEyMjdhZmM4ZDciLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTc1MDA5NSwiZXhwIjoxNjgxMzAyMDk1fQ.DdJFdW9O1scrS_Y7hA0AAEbjLFRq6FLfafkhL-eiobE

###

// Get all cabins
GET {{baseURL}}/cabins
Authorization: Bearer {{bearer}}

###

GET {{baseURL}}/cabins/owned
Authorization: Bearer {{bearer}}

###

// Create new cabin
POST {{baseURL}}/cabins
Content-Type: application/json
Authorization: Bearer {{bearer}}

{
    "address": "Rasmus' cabin",
    "size": 250,
    "sauna": true,
    "beach": true,
    "rent": 300
}

###

// Patch/modify cabin data
PATCH {{baseURL}}/cabins/63342c4633edd0eaf467fd4b
Content-Type: application/json
Authorization: Bearer {{bearer}}

{
    "address": "Cabin street"
}

###

// Delete cabin
DELETE {{baseURL}}/cabins/6334055a161a5d84aa2d2fae
Authorization: Bearer {{bearer}}
