@baseURL = http://localhost:3030

###

GET {{baseURL}}/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzg1OGVmYWVlYzEyMjdhZmM4ZDIiLCJlbWFpbCI6ImphbmUuZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NDE4NjU4MiwiZXhwIjoxNjY0MjcyOTgyfQ.pxPP7Mx_OXAlVjGxhS67gaDXyjLWK9HCMfK1PlzTqoM

###

POST {{baseURL}}/users/login
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@arcada.fi",
    "password": "Password123"
}

###

POST {{baseURL}}/users/register
Content-Type: application/json

{
    "firstname": "Rasmus",
    "lastname": "Doe",
    "email": "rasmus.doe@arcada.fi",
    "password": "1234567"
}