@baseURL = http://localhost:3030
@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzMxNzkxNGVmYWVlYzEyMjdhZmM4ZDciLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NDM2NDMxMiwiZXhwIjoxNjc5OTE2MzEyfQ.LVNhihPC96dE6zVBFMKv7C42TIygKoN2AZ7SH3P7XIw


###

GET {{baseURL}}/users
Authorization: Bearer {{bearer}}

###

POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "john.doe@arcada.fi",
    "password": "Password123"
}

###

POST {{baseURL}}/users/register
Content-Type: application/json

{
    "firstname": "Rasmus",
    "lastname": "Doe",
    "email": "rasmus.doe@arcada.fi",
    "password": "1234567"
}