@baseURL = http://localhost:3030
@bearer = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2MzNmMTFjYTg3NTA2MDQwNzUwNTZkY2UiLCJlbWFpbCI6ImpvaG4uZG9lQGFyY2FkYS5maSIsImlhdCI6MTY2NTA3NzgzOCwiZXhwIjoxNjgwNjI5ODM4fQ.0Z9gYjtcogS1qQt7NVPB7Pd9GKxxhmdPmJSG6GlaHko


###

GET {{baseURL}}/users
Authorization: Bearer {{bearer}}

###

POST {{baseURL}}/users/login
Content-Type: application/json

{
    "email": "john.doe@arcada.fi",
    "password": "1234567"
}

###

POST {{baseURL}}/users/register
Content-Type: application/json

{
    "firstname": "John",
    "lastname": "Doe",
    "email": "john.doe@arcada.fi",
    "password": "1234567"
}